apiVersion: v1
kind: Service
metadata:
  name: pushbot-service
  namespace: monitoring
  #  annotations:
  #    prometheus.io/scrape: 'true'
  #  prometheus.io/port:   '9090'

spec:
  selector:
    app: pushbot
  type: LoadBalancer
  ports:
    - port: 7777
      targetPort: 7777
