---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushbot-deployment
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushbot
  template:
    metadata:
      labels:
        app: pushbot
    spec:
      containers:
        - name: pushbot
          image: m1ke/pushbot:latest
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          args:
              - " --config '/root/config/config.yaml'"
          ports:
            - containerPort: 7777
          volumeMounts:
            - name: pushbot-config-volume
              mountPath: /root/config
      volumes:
        - name: pushbot-config-volume
          configMap:
            defaultMode: 420
            name: pushbot-config
            items:
            - key: config.yaml
              path: config.yaml

